# Generated by Django 3.0.3 on 2020-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200226_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='body',
            field=models.CharField(default='dupa', max_length=128),
        ),
    ]
