# Generated by Django 3.0.3 on 2020-02-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200226_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['upvotes']},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='body',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.Comment'),
        ),
        migrations.AddField(
            model_name='rating',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='events.Event'),
        ),
    ]
